name: Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  build-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install cmake gcovr ninja-build -y
      - name: Run tests with coverage options
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=ON
          cmake --build . -- -j$(nproc)
          ctest
          cmake --build . --target coverage
      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./build/coverage.info
          flags: unittests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
